# basic options,i can say what ever here
title: New-awesome-blog
author: Smart Guy
email: your-email@domain.com
description: A lovely wonderful blog
twitter_username: jekyllrb
github_username: cheeluoqinger
theme: minima
#Build settings
markdown: kramdown
